### ISSUE TITLE
 问下 Elasticsearch 模块能禁用吗

### ISSUE THREAD

**Issue by yangxuan8282** [eiblog/eiblog#2]
再起一个 Elasticsearch 感觉有点费资源了，试了一下 docker-compose.yml 里去掉 Elasticsearch 容器部分的话会报错

**Comment by yangxuan8282** [comment]
建了个新镜像可以访问了，不过 opensearch 还是搜索的作者的网站

**Comment by deepzz0** [comment]
@yangxuan8282 你好，如果弃用 Elasticsearch，那么你的 opensearch 也没了作用，就没有了搜索功能。

opensearch 需要改配置：
```
# 运行模式
mode:
  enablehttp: true
  httpport: 9000
  enablehttps: false
  httpsport: 443
  certfile: conf/certs/domain.pem
  keyfile: conf/certs/domain.key
  domain: deepzz.com
```
将 domain 改为你的，如果仍然是作者的，请强制刷新 https://example.com/opensearch.xml。

Elasticsearch，暂时没有关掉功能，你可以手动注释代码或html标签
